### ISSUE TITLE
TODO 11-01-2021

### ISSUE THREAD

**Issue by iamslv** [Andreea77/timetable#4]
>test1.py

- [x] Fix the all constraints at once solving issue (lines  306-314)
- [x] Automate the hardcoded DataFrame splitting (lines 122-131).
- [x] Discuss the case where a course is taught by more than one teacher with the team and decide on next action points.
